### ISSUE TITLE
n_ancova does not return actual power!

### ISSUE THREAD

**Issue by kkmann** [goseberg/samplesizr#2]
```
samplesizr::n_ancova(.05, .2, r = 1, effect = .2, corr = .5, sd = 1)
Sample size calculation for ANCOVA comparing two 
samples (two-sided alternative).
Guenther/Schouten correcture performed.

Input Parameters 

Significance level : 0.05
Desired Power : 20.00 %
Effect size : 0.20
Correlation : 0.50
Standard deviation : 1.00
Allocation : 1.00 

Results of sample size calculation 

n Group X : 48
n Group Y : 48
n Total : 96
Resulting Power : WARNING. See Documentation.
```

Is this intended behaviour? Resulting power should be slightly larger than the desired one, should it not?

**Comment by goseberg** [comment]
Solution Ideas by now :

1. Ask MK how to calculate exact power.
2. Look up in Chung, Show: Sample Size Calculations in Clinical Research, Second Edition (Chapman & Hall/CRC Biostatistics Series)
3. Use a Data Simulation Approach sampling from a multivariate gaussian with given covariance Matrix.
Problem: Could be to 'intense' to calculate for a low performance web app.
